### ISSUE TITLE
Some errors in data.py file

### ISSUE THREAD

**Issue by alishakiba** [sveitser/kaggle_diabetic#1]
Hi there,

There are two errors in file `data.py`:
- on line 202, the method `load_image_uint` is not defined. However, the project works well since the method `std` defined on line 196 is never called in the project, :). I have searched for the method, but it does not exist.
- on line 149 in method `load_perturbed`, the file `util` is not imported, This can be solved by importing `impot util` just before that line.

Thanks for sharing your ideas.

**Comment by sveitser** [comment]
Thanks. Yes as you have noticed these functions currently  aren't used when the code is run. You would only need the `std` function if you were to compute the standard deviation of a different dataset.
