### ISSUE TITLE
ImportError: No module named configs.c_128_5x5_32

### ISSUE THREAD

**Issue by danieleewww** [sveitser/kaggle_diabetic#10]
Hello Mathis, please check the message below executed with train_nn.py with the importerror:No module named configs.c_128_5x5_32 

```
(kaggleDR-env)danieleewww@Ubuntuwww:~/Documents/KaggleDR$ ./make_kaggle_solution.sh
Resizing images in data/train to data/train_medium, this takes a while.
batch  1 / 71
batch  2 / 71
.......
batch 70 / 71
batch 71 / 71
done
Using gpu device 0: GeForce GTX 970 (CNMeM is disabled)
/home/danieleewww/Documents/KaggleDR/src/theanopip/theano/tensor/signal/downsample.py:5: UserWarning: downsample module has been moved to the pool module.
  warnings.warn("downsample module has been moved to the pool module.")
Traceback (most recent call last):
  File "train_nn.py", line 40, in <module>
    main()
  File "/home/danieleewww/anaconda2/envs/kaggleDR-env/lib/python2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/home/danieleewww/anaconda2/envs/kaggleDR-env/lib/python2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/home/danieleewww/anaconda2/envs/kaggleDR-env/lib/python2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/danieleewww/anaconda2/envs/kaggleDR-env/lib/python2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "train_nn.py", line 17, in main
    config = util.load_module(cnf).config
  File "/home/danieleewww/Documents/KaggleDR/util.py", line 33, in load_module
    return importlib.import_module(mod.replace('/', '.').split('.py')[0])
  File "/home/danieleewww/anaconda2/envs/kaggleDR-env/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named configs.c_128_5x5_32
```

my pip list:

```
(kaggleDR-env)danieleewww@Ubuntuwww:~/Documents/KaggleDR$ pip list
click (3.3)
decorator (4.0.6)
funcsigs (0.4)
ghalton (0.6)
joblib (0.9.4)
Lasagne (0.1.dev0, /home/danieleewww/Documents/KaggleDR/src/lasagne-master)
matplotlib (1.4.3)
mock (1.3.0)
networkx (1.10)
nolearn (0.6a0.dev0, /home/danieleewww/Documents/KaggleDR/src/nolearn-master)
nose (1.3.7)
numpy (1.10.4)
pandas (0.17.1)
pbr (1.8.1)
Pillow (2.7.0)
pip (7.1.2)
pyparsing (2.0.7)
python-dateutil (2.4.2)
pytz (2015.7)
PyYAML (3.11)
scikit-image (0.11.3)
scikit-learn (0.16.1)
scipy (0.15.1)
setuptools (19.2)
SharedArray (0.2)
six (1.10.0)
tabulate (0.7.5)
Theano (0.8.0.dev0, /home/danieleewww/Documents/KaggleDR/src/theanopip)
wheel (0.26.0)
```

**Comment by sveitser** [comment]
Do the files `configs/c_128_5x5_32.py` and `configs/__init__.py` exist?

If they do, what's the output of running `python --version` and `python -c "import sys; print(sys.path)"`?

**Comment by danieleewww** [comment]
Hi Mathis: 

(kaggleDR-env)danieleewww@Ubuntuwww:~/Documents/KaggleDR$ python --version 

Python 2.7.11 :: Continuum Analytics, Inc.

(kaggleDR-env)danieleewww@Ubuntuwww:~/Documents/KaggleDR$ python -c "import sys; print(sys.path)"

['', '/home/danieleewww/Documents/KaggleDR/src/lasagne-master', '/home/danieleewww/Documents/KaggleDR/src/nolearn-master', '/home/danieleewww/Documents/KaggleDR/src/theanopip', '/home/danieleewww/anaconda2/envs/kaggleDR-env/lib/python27.zip', '/home/danieleewww/anaconda2/envs/kaggleDR-env/lib/python2.7', '/home/danieleewww/anaconda2/envs/kaggleDR-env/lib/python2.7/plat-linux2', '/home/danieleewww/anaconda2/envs/kaggleDR-env/lib/python2.7/lib-tk', '/home/danieleewww/anaconda2/envs/kaggleDR-env/lib/python2.7/lib-old', '/home/danieleewww/anaconda2/envs/kaggleDR-env/lib/python2.7/lib-dynload', '/home/danieleewww/anaconda2/envs/kaggleDR-env/lib/python2.7/site-packages', '/home/danieleewww/anaconda2/envs/kaggleDR-env/lib/python2.7/site-packages/setuptools-19.2-py2.7.egg']

**Comment by sveitser** [comment]
What do you get if you run `ls -l configs`? It looks like the files in the `configs` directory are missing and that's why it can't import them.

**Comment by danieleewww** [comment]
ls: cannot access configs: No such file or directory

**Comment by danieleewww** [comment]
no configs/c_128_5x5_32.py and configs/**init**.py  generated

**Comment by sveitser** [comment]
These files aren't generated they are part of this repository.

Not sure why they aren't there, maybe the files were copied from one place to another without the `-r` flag?

In any case, it's probably easiest if you start with a fresh git checkout so you have all the files.

**Comment by danieleewww** [comment]
Hi Mathis:

it's my fault with copying files in your master folder.

thanks.

Daniel

**Comment by sveitser** [comment]
No problem!
