### ISSUE TITLE
Error with CudaConvnet mode

### ISSUE THREAD

**Issue by lincoln2010** [sveitser/kaggle_diabetic#4]
While executing the programme in CudaCovnet mode, there are errors: 
  File "/home/lincoln/desktop/DRCuda/layers.py", line 24, in <module>
    Pool2DLayer = lasagne.layers.cuda_convnet.Pool2DLayer
AttributeError: 'module' object has no attribute 'Pool2DLayer'
After looking into the problem, lthere isn't a class named Pool2DLayer in cuda_convnet.py from lasagne/layers/

**Comment by sveitser** [comment]
Have you tried with the `deterministic` branch?

**Comment by lincoln2010** [comment]
Yes, the same problem occurred. And this is because there exist no class named Pool2DLayer in cuda_convnet.py from lasagne/layers

**Comment by sveitser** [comment]
I can't find any reference to that layer in this file https://github.com/sveitser/kaggle_diabetic/blob/deterministic/layers.py

**Comment by lincoln2010** [comment]
Thank you very much for your reply! Maybe there are some problems with the lasagne installation. Could you provide generated files like weights so it may not need to take too much time to try the amazing program? : )

**Comment by sveitser** [comment]
It's kind of tricky because I only have trained weights for both networks for the `master` branch. And with cuda-convnet or CPU the shapes of the layers don't match exactly. I'll see what I can.
