### ISSUE TITLE
error in pip install -r requirements.txt

### ISSUE THREAD

**Issue by danieleewww** [sveitser/kaggle_diabetic#7]
Hello Mathis,

this is the error code when "
pip install -r requirements.txt" , any suggest on this (this in OSX)

building 'SharedArray' extension
    gcc -fno-strict-aliasing -I/Users/Daniel/anaconda2/envs/kaggle1/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/Daniel/anaconda2/envs/kaggle1/include/python2.7 -c /var/folders/x3/j4dr5xhx1sq08x5q4r8kzdyw0000gn/T/pip-1me7Jj-build/src/shared_array.c -o build/temp.macosx-10.5-x86_64-2.7/var/folders/x3/j4dr5xhx1sq08x5q4r8kzdyw0000gn/T/pip-1me7Jj-build/src/shared_array.o
    /var/folders/x3/j4dr5xhx1sq08x5q4r8kzdyw0000gn/T/pip-1me7Jj-build/src/shared_array.c:24:10: fatal error: 'numpy/arrayobject.h' file not found
    #include <numpy/arrayobject.h>
             ^
    1 error generated.
    error: command 'gcc' failed with exit status 1

**Comment by sveitser** [comment]
Looks like some numpy files can't be found. You could try installing numpy first.

```
pip install numpy==1.9.2
```

then the other requirements

```
pip install -r requirements.txt
```

**Comment by danieleewww** [comment]
Hello Mattis:
tried many different ways including your suggestion, the only error still @ building sharedarray extention,  
all other packages are all built without any errors.  Is there any go around without using 'import sharedarray as sa' in your code?

**Comment by sveitser** [comment]
We would have to write a different Iterator and it would slow things down considerably. I think it should be possible to build SharedArray though.
You could try building it manually.

```
git clone http://parad0x.org/git/python/shared-array
cd shared-array
git checkout 0.2
python setup.py build
python setup.py install
```

If the same error still occurs, maybe adding `include_dirs=[numpy.get_include()]` in `setup.py` like in this SO post http://stackoverflow.com/a/14657667/469992 would help?

**Comment by danieleewww** [comment]
still could not install either sharedarray 0.2 or 0.3 in OSX; switched to Linux14.04LTS and used the pip install the packages(file attached) individually and able to proceed to the next step without env. setup issue.
[Kagglepilot1.txt](https://github.com/sveitser/kaggle_diabetic/files/75844/Kagglepilot1.txt)
